version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: airbnb-backend-prod
    ports:
      - "18047:5000"
    environment:
      - MONGO_URI=mongodb+srv://bhaktaravin:bhaktaravin@cluster0.lnxnu.mongodb.net/sample_airbnb?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    restart: unless-stopped
    networks:
      - airbnb-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: airbnb-frontend-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://100.103.37.7:18047
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge
