version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: airbnb-backend-prod
    ports:
      - "18047:5000"
    environment:
      - MONGO_URI=mongodb://bhaktaravin:bhaktaravin@cluster0-shard-00-00.lnxnu.mongodb.net:27017,cluster0-shard-00-01.lnxnu.mongodb.net:27017,cluster0-shard-00-02.lnxnu.mongodb.net:27017/sample_airbnb?ssl=true&replicaSet=atlas-l540kb-shard-0&authSource=admin&retryWrites=true&w=majority
      - PORT=5000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - airbnb-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: airbnb-frontend-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://100.103.37.7:18047
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge
